# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# Add current directory to path
current_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['app_launcher.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('Settings', 'Settings'),  # Include Settings directory
    ],
    hiddenimports=[
        # Core modules
        'utils',
        'utils.shared_utils',
        'utils.utils',
        'utils.scan_helpers',
        'utils.app_context',
        'utils.text_helpers',
        'utils.debug_helpers',
        'utils.settings_helpers',
        'mkvapp',
        'mkvapp.lifecycle',
        'mkvapp.core',
        'mkvapp.ui_config',
        'config',
        'config.smart_config_manager',
        'config.config_access',
        'config.schema_utils',
        'config.sync_utils',
        'menus',
        'menus.popup',
        'menus.create_gui_menu',
        'menus.menu_registry',
        'menus.menu_yaml_exporter',
        'menus.init_loader',
        'binding',
        'binding.manager',
        'binding.registry',
        'binding.resolver',
        'binding.handlers',
        'binding.events',
        'binding.constants',
        'binding.helpers',
        'binding.widget_scan',
        'widgets',
        'widgets.base_textbox',
        'widgets.filter_listbox',
        'widgets.config_frame',
        'widgets.debug_frame',
        'widgets.entry_factory',
        'widgets.smart_entry',
        'widgets.status_slot',
        'widgets.reg_viewer',
        'widgets.layout_primitives',
        'widgets.pop_button',
        'widgets.data_inspector',
        'widgets.debug_console',
        'widgets.debug_panel',
        'widgets.injects',
        'actions',
        'actions.lb_files',
        'actions.lb_files.videos',
        'actions.lb_files.videos.vids_mgr',
        'actions.lb_files.videos.video_inspector',
        'actions.lb_files.subtitles',
        'actions.lb_files.subtitles.sub_mgr',
        'actions.tb_info',
        'actions.tb_folders',
        'actions.tb_debug',
        'actions.tb_settings',
        'actions.tools',
        'actions.help',
        'actions.tbox',
        'actions.lbox',
        'actions.tb_test',
        'decorators',
        'decorators.decorators',
        # Third-party modules (excluding problematic ones)
        'customtkinter',
        'darkdetect',
        'PIL',
        'numpy',
        'moviepy',
        'langdetect',
        'argostranslate',
        'auditok',
        'ffsubsync',
        'send2trash',
        'language_data',
        'langcodes',
        'thinc',
        'spacy',
        # Additional modules that might be missed
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'queue',
        'threading',
        'subprocess',
        'pathlib',
        'json',
        'yaml',
        'logging',
        'functools',
        'itertools',
        'collections',
        'datetime',
        'time',
        'os',
        'sys',
        'platform',
        'shutil',
        'glob',
        'fnmatch',
        're',
        'string',
        'math',
        'random',
        'hashlib',
        'base64',
        'binascii',
        'struct',
        'array',
        'ctypes',
        'mmap',
        'msvcrt',
        'winsound',
        'winreg',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude problematic modules
        'webrtcvad',
        # 'cv2',  # Uncommented to include OpenCV
        'torch',  # PyTorch is large and complex
        'tensorflow',  # TensorFlow is also complex
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MKVApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
